### ISSUE TITLE
Build fails for scala 2.11 and 2.13

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/balta#15]
## Describe the bug
Build fail for scala 2.11 and 2.13.

## To reproduce
```
sbt ++2.13.11 test doc
sbt ++2.11.12 test doc
```

## Expected behavior
Build pass.

**Comment by miroslavpojer** [comment]
Retested on master and no problem found.

**Comment by benedeki** [comment]
> Retested on master and no problem found.

Then you could have closed this ticket 😉
