### ISSUE TITLE
Failure when dbConnection not created

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/balta#23]
## Describe the bug
When calling `sbt test` command on local env without accessible `atum_db`, dbConnection init fails.
In the `test` method in the finally block, there is no check that dbConnection has been successfully initialized.

**Comment by benedeki** [comment]
I don't recall what exactly is the problem here. If the DB is not available, it's fine to fail isn't it?

**Comment by miroslavpojer** [comment]
> I don't recall what exactly is the problem here. If the DB is not available, it's fine to fail isn't it?

The problem is that the command `test` runs unit tests, which should be immune to the database's availability.

**Comment by benedeki** [comment]
> > I don't recall what exactly is the problem here. If the DB is not available, it's fine to fail isn't it?
> 
> The problem is that the command `test` runs unit tests, which should be immune to the database's availability.

Wait, what? One writes DB tests, DB not available, test fails. Seems like a correct and expected behavior.

**Comment by miroslavpojer** [comment]
I did a re-test of the problem.
No DB created on local:
- sbt test - **PASSED**
- sbt testIT - **FAILED as expected**
- sbt testDB - **FAILED as expected**
DB instance created on local:
- sbt test - **PASSED**
- sbt testIT - **PASSED**
- sbt testDB - **PASSED**
